name: "my-job"

on: 
  push: 
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hola Mundo"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hola Mundo"
