name: "my-job"

on: 
  push: 
    branches:
      - main
      - stage

jobs:
  my-job:
    runs-on: ubuntu-latest
    env: 
      FOO: bar
      BAR: foo
    steps:
      - name: Say hello
        run: echo "Hola Mundo stage $FOO" 
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: my-job
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hola Mundo $BAR" 
